#pragma once

#include "CoImageDef.h"	    //<vho> adjust some #define

namespace cvlib 
{

	//! 
	enum ENUM_CVLIB_IMG_FORMATS
	{
		CVLIB_IMG_FORMAT_UNKNOWN,
#if CVLIB_IMG_SUPPORT_BMP
		CVLIB_IMG_FORMAT_BMP,
#endif
#if CVLIB_IMG_SUPPORT_GIF
		CVLIB_IMG_FORMAT_GIF,
#endif
#if CVLIB_IMG_SUPPORT_JPG
		CVLIB_IMG_FORMAT_JPG,
#endif
#if CVLIB_IMG_SUPPORT_PNG
		CVLIB_IMG_FORMAT_PNG,
#endif
#if CVLIB_IMG_SUPPORT_MNG
		CVLIB_IMG_FORMAT_MNG,
#endif
#if CVLIB_IMG_SUPPORT_ICO
		CVLIB_IMG_FORMAT_ICO,
#endif
#if CVLIB_IMG_SUPPORT_TIF
		CVLIB_IMG_FORMAT_TIF,
#endif
#if CVLIB_IMG_SUPPORT_TGA
		CVLIB_IMG_FORMAT_TGA,
#endif
#if CVLIB_IMG_SUPPORT_PCX
		CVLIB_IMG_FORMAT_PCX,
#endif
#if CVLIB_IMG_SUPPORT_WBMP
		CVLIB_IMG_FORMAT_WBMP,
#endif
#if CVLIB_IMG_SUPPORT_WMF
		CVLIB_IMG_FORMAT_WMF,
#endif
#if CVLIB_IMG_SUPPORT_J2K
		CVLIB_IMG_FORMAT_J2K,
#endif
#if CVLIB_IMG_SUPPORT_JBG
		CVLIB_IMG_FORMAT_JBG,
#endif
#if CVLIB_IMG_SUPPORT_JP2
		CVLIB_IMG_FORMAT_JP2,
#endif
#if CVLIB_IMG_SUPPORT_JPC
		CVLIB_IMG_FORMAT_JPC,
#endif
#if CVLIB_IMG_SUPPORT_PGX
		CVLIB_IMG_FORMAT_PGX,
#endif
#if CVLIB_IMG_SUPPORT_PNM
		CVLIB_IMG_FORMAT_PNM,
#endif
#if CVLIB_IMG_SUPPORT_RAS
		CVLIB_IMG_FORMAT_RAS,
#endif
		CVLIB_IMG_MAX_FORMATS
	};

}